server:
  port: 7003

app:
  service:
    name: User Service

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  validity: 180000
  info: info

spring:
  application:
    name: user-svc-dev
#  profiles:
#    active: test
  data:
    mongodb:
      uri: mongodb://local-mongo-usr:local-mongo-pwd@localhost:27017/user-svc?authSource=admin
      database: user-svc

  redis:
    host: localhost
    port: 6379
    password: secure_password

#values configs
department-svc-feign-client: department-svc-dev
document-svc-feign-client: document-svc-dev
