#spring.config.import=optional:configserver:
#spring.cloud.config.fail-fast=true
##spring.cloud.config.enabled=false
#spring.application.name=registry-svc

logging:
  level:
    org:
      springframework:
        security: DEBUG
